#!/bin/bash
NAME="My_information"                               # Name of the application
#TODO: relative path
DJANGODIR=/webapp/My_information/src               # Django project directory
GUNICORN=/webapp/venv/bin/gunicorn
ENV_ACT=/webapp/venv/bin/activate
SOCKFILE=/webapp/My_information/run/gunicorn.socki                 # we will communicte using this unix socket
USER=webapp                                               # the user to run as
GROUP=nginx                                         # the group to run as
NUM_WORKERS=3                                       # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=fortytwo_test_task.settings  # which settings file should Django use
DJANGO_WSGI_MODULE=fortytwo_test_task.wsgi          # WSGI module name
echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR/
source $ENV_ACT

cd $DJANGODIR
source ../../venv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec $GUNICORN ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --bind=unix:$SOCKFILE --user=$USER --group=$GROUP \
  --log-level=debug \
  --log-file=-